//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sauron.Services.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class ServicesSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ServicesSettings defaultInstance = ((ServicesSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ServicesSettings())));
        
        public static ServicesSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\\\DownloadedRepositories\\\\{0}\\\\{1}\\\\")]
        public string DownloadRepositotyPathTemplate {
            get {
                return ((string)(this["DownloadRepositotyPathTemplate"]));
            }
        }
    }
}
